<a href="https://colab.research.google.com/github/YolandaMDavis/cs109a-fall2020/blob/yolanda-eda/Data_Merge_Milestone_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
%matplotlib inline
import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
DATA_ROOT = '/content/drive/My Drive/Final-Project-for-CS109a/data_prelim/'

**Loading of Boston DataSets**

In [3]:
boston_crime_covid_df = pd.read_csv(DATA_ROOT + 'boston_crime_covid_yolanda.csv').set_index(['INCIDENT_NUMBER','OFFENSE_CODE']).drop(columns=["Unnamed: 0","SHOOTING"])
boston_crime_covid_df.head()

                               OFFENSE_DESCRIPTION  ...       GEOHASH
INCIDENT_NUMBER OFFENSE_CODE                        ...
TESTTEST2       423           ASSAULT - AGGRAVATED  ...  000000000000
202062971       423           ASSAULT - AGGRAVATED  ...  000000000000
202061413       423           ASSAULT - AGGRAVATED  ...  000000000000
202060210       423           ASSAULT - AGGRAVATED  ...  000000000000
I192078179      423           ASSAULT - AGGRAVATED  ...  drt2z1dzcvbc

[5 rows x 18 columns]

In [4]:
boston_crime_socio_eco_df = pd.read_csv(DATA_ROOT + 'boston_crime_james.csv').set_index(['INCIDENT_NUMBER','OFFENSE_CODE'])
boston_crime_socio_eco_df.head()

                                   OFFENSE_DESCRIPTION  ... LOCAL_PROP_VALUES
INCIDENT_NUMBER OFFENSE_CODE                            ...
S97333701       3301                    VERBAL DISPUTE  ...      4.430931e+06
I20210846       3201          PROPERTY - LOST/ MISSING  ...      2.996402e+07
I20207883       3115                INVESTIGATE PERSON  ...      1.417106e+07
I192078622      619                 LARCENY ALL OTHERS  ...      3.620904e+07
I192078606      3201                   PROPERTY - LOST  ...      3.620904e+07

[5 rows x 23 columns]

In [5]:
boston_elws_df = pd.read_csv(DATA_ROOT + 'boston_election_locations_weather_sunset_ramzi_final.csv').set_index(['INCIDENT_NUMBER','OFFENSE_CODE']).drop(columns=["Unnamed: 0","Unnamed: 0.1"])
boston_elws_df.head()

                             OFFENSE_DESCRIPTION DISTRICT  ... SNOW  NIGHT
INCIDENT_NUMBER OFFENSE_CODE                               ...
S97333701       3301              VERBAL DISPUTE       C6  ...  0.0      0
202050885       3301              VERBAL DISPUTE       B3  ...  0.0      1
202050877       3301              VERBAL DISPUTE       B2  ...  0.0      1
202050871       3301              VERBAL DISPUTE       B3  ...  0.0      1
202050857       3301              VERBAL DISPUTE       B2  ...  0.0      1

[5 rows x 21 columns]

In [6]:
print(boston_crime_covid_df.shape)
print(boston_crime_socio_eco_df.shape)
print(boston_elws_df.shape)

(523627, 18)
(523518, 23)
(485568, 21)

**Loading New York City Data Sets**

In [7]:
new_york_crime_covid_df = pd.read_csv(DATA_ROOT + 'new_york_crime_covid_yolanda.csv').set_index('CMPLNT_NUM').drop(columns=["Unnamed: 0"])
new_york_crime_covid_df.head()

           BOROUGH CMPLNT_FR_DT  ...       GEOHASH COVID_PERIOD
CMPLNT_NUM                       ...
843609180    BRONX   08/24/2020  ...  dr72r17k3w6x            1
702473966    BRONX   09/23/2020  ...  dr72jubqryef            1
708300720    BRONX   09/25/2020  ...  dr72jtrrxqq9            1
577206559    BRONX   09/28/2020  ...  dr72xm6p4e0j            1
298610543    BRONX   09/26/2020  ...  dr782108pq2c            1

[5 rows x 21 columns]

In [8]:
new_york_crime_socio_eco_df = pd.read_csv(DATA_ROOT + 'nyc_crime_local_prop_values.csv').set_index('CMPLNT_NUM')
new_york_crime_socio_eco_df.head()

            ADDR_PCT_CD BORO_NM  ...       GEOHASH LOCAL_PROP_VALUES
CMPLNT_NUM                       ...
972326799            81     NaN  ...  dr5rmtq3w0gr     261626.291626
376304873            52     NaN  ...  dr72wc598dex     486793.141491
299326203            75     NaN  ...  dr5rr4euvm4j     295180.421053
674946147           121     NaN  ...  dr5r0md8uns2      47175.295567
416422620           101     NaN  ...  dr5wcqycd6g0     143857.197802

[5 rows x 37 columns]

In [9]:
new_york_elws_df = pd.read_csv(DATA_ROOT + 'nyc_election_locations_weather_sunset_ramzi_final.csv').set_index(["CMPLNT_NUM"]).drop(columns=["Unnamed: 0"])
new_york_elws_df.head()

              BOROUGH CMPLNT_FR_DT  ... VIOLENT_CRIME OFFENSE_TYPE
CMPLNT_NUM                          ...
843609180       BRONX   08/24/2020  ...             0   Harassment
397173953       BRONX   08/24/2020  ...             0   Harassment
308319126   MANHATTAN   08/24/2020  ...             0   Harassment
133816979    BROOKLYN   08/24/2020  ...             0   Harassment
284953252    BROOKLYN   08/24/2020  ...             0   Harassment

[5 rows x 25 columns]

In [10]:
print(new_york_crime_covid_df.shape)
print(new_york_crime_socio_eco_df.shape)
print(new_york_elws_df.shape)

(306288, 21)
(306656, 37)
(306288, 25)

**Boston Data Merge and Cleansing**

In [11]:
crime_covid_df = boston_crime_covid_df[["DISTRICT","YEAR","MONTH","DAY_OF_WEEK","HOUR","LATITUDE","LONGITUDE","COVID_PERIOD","VIOLENT_CRIME","OFFENSE_TYPE"]]
crime_socio_eco_df = boston_crime_socio_eco_df[["WHITE","BLACK","HISPANIC","ASIAN","OTHER","16-19-EMPLOYMENT","20-34-EMPLOYMENT","MEDIAN_INCOME","GEOHASH","LOCAL_PROP_VALUES"]]
boston_elws_df.dropna(subset=['DISTRICT'], inplace=True)
crime_elws_df = boston_elws_df[["Streetlight_density","Police_Station_Distance","Hospitals_Distance","College_Univ_Distance","election","PRCP","SNOW","NIGHT"]]
boston_crime_analysis_data_df = crime_covid_df.join(crime_socio_eco_df).join(crime_elws_df)
boston_crime_analysis_data_df.head()

                             DISTRICT  YEAR  MONTH  ...  PRCP  SNOW  NIGHT
INCIDENT_NUMBER OFFENSE_CODE                        ...
102091671       2647               B3  2019     11  ...  0.08   0.0    0.0
102095489       3115              E18  2019     11  ...  0.00   0.0    0.0
102096818       3126               A1  2019     11  ...  0.00   0.0    1.0
120200013       2403               A1  2020      1  ...  0.00   0.0    1.0
120200242       3115               D4  2020      1  ...  0.11   0.0    1.0

[5 rows x 28 columns]

In [12]:
#dropping NA / -1 lat lon values
boston_crime_analysis_data_df.dropna(subset=['LATITUDE','LONGITUDE'], inplace=True)
boston_crime_analysis_data_df = boston_crime_analysis_data_df[(boston_crime_analysis_data_df["LATITUDE"] != -1) & (boston_crime_analysis_data_df["LONGITUDE"] != -1) ]

# dropping External district due to missing socio-economic data
boston_crime_analysis_data_df = boston_crime_analysis_data_df[boston_crime_analysis_data_df["DISTRICT"] != "External"]

**New York City Data Merge and Cleansing**

In [13]:
crime_covid_df = new_york_crime_covid_df[["BOROUGH","YEAR","MONTH","DAY_OF_WEEK","HOUR","Latitude","Longitude","COVID_PERIOD","VIOLENT_CRIME","OFFENSE_TYPE","GEOHASH"]]
crime_socio_eco_df = new_york_crime_socio_eco_df[["LOCAL_PROP_VALUES"]]
crime_elws_df = new_york_elws_df[["Streetlight_density","Police_Station_Distance","Hospitals_Distance","College_Univ_Distance","election","PRCP","SNOW","NIGHT"]]
new_york_crime_analysis_data_df = crime_covid_df.join(crime_socio_eco_df).join(crime_elws_df)
new_york_crime_analysis_data_df.head()

           BOROUGH  YEAR  MONTH DAY_OF_WEEK  ...  election  PRCP  SNOW  NIGHT
CMPLNT_NUM                                   ...
843609180    BRONX  2020      8      Monday  ...      0.11  0.00   0.0      1
702473966    BRONX  2020      9   Wednesday  ...      0.11  0.00   0.0      0
708300720    BRONX  2020      9      Friday  ...      0.11  0.00   0.0      0
577206559    BRONX  2020      9      Monday  ...      0.11  0.02   0.0      0
298610543    BRONX  2020      9    Saturday  ...      0.11  0.00   0.0      1

[5 rows x 20 columns]

In [14]:
#dropping NA / -1 lat lon values
new_york_crime_analysis_data_df.dropna(subset=['Latitude','Longitude'], inplace=True)
new_york_crime_analysis_data_df = new_york_crime_analysis_data_df[(new_york_crime_analysis_data_df["Latitude"] != -1) & (new_york_crime_analysis_data_df["Longitude"] != -1) ]

**Final Data Check and Save**

In [15]:
# Final checkpoint before writing out final data set
print(boston_crime_analysis_data_df.shape)
print(boston_crime_analysis_data_df.isnull().sum())

(502013, 28)
DISTRICT                       0
YEAR                           0
MONTH                          0
DAY_OF_WEEK                    0
HOUR                           0
LATITUDE                       0
LONGITUDE                      0
COVID_PERIOD                   0
VIOLENT_CRIME                  0
OFFENSE_TYPE                   0
WHITE                          0
BLACK                          0
HISPANIC                       0
ASIAN                          0
OTHER                          0
16-19-EMPLOYMENT               0
20-34-EMPLOYMENT               0
MEDIAN_INCOME                  0
GEOHASH                        0
LOCAL_PROP_VALUES              0
Streetlight_density         9507
Police_Station_Distance     9507
Hospitals_Distance          9507
College_Univ_Distance       9507
election                    9507
PRCP                        9507
SNOW                       10242
NIGHT                       9507
dtype: int64

In [16]:
# Final checkpoint before writing out final data set
print(new_york_crime_analysis_data_df.shape)
print(new_york_crime_analysis_data_df.isnull().sum())

(306288, 20)
BOROUGH                    0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
Latitude                   0
Longitude                  0
COVID_PERIOD               0
VIOLENT_CRIME              0
OFFENSE_TYPE               0
GEOHASH                    0
LOCAL_PROP_VALUES          0
Streetlight_density        0
Police_Station_Distance    0
Hospitals_Distance         0
College_Univ_Distance      0
election                   0
PRCP                       0
SNOW                       0
NIGHT                      0
dtype: int64